apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbox
  labels:
    app: chatbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbox
  template:
    metadata:
      labels:
        app: chatbox
    spec:
      containers:
      - name: chatbox
        image: lappiey/chatbox-go:v1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: my-registry-secret   




---
apiVersion: v1
kind: Service
metadata:
  name: chatbox
spec:
  type: LoadBalancer 
  selector:
    app: chatbox
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
      # nodePort: 30001  
