

name: ChatBox

on:
  
  pull_request:
    branches: [ "develop" ]
  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.5'

   
    - name: Test
      run: go test -v ./...  
